### ISSUE TITLE
关于DiSCo-SLAM的复现问题，想请教下大佬

### ISSUE THREAD

**Issue by BIT-TYJ** [NatureLan-sudo/NatureLan-sudo#1]
Hello, 俺也是BIT的研究生（自动化学院）。
这两天在复现DiSCo-SLAM, 自己解决了一下编译问题（主要是libnabo::nabo找不到）。
结果在运行他的kitti_08.bag时候会出错(launch文件的两行替换过了)，不知道大佬有没有类似问题。
_[ WARN] [1662382090.137015156]: Point cloud timestamp not available, deskew function disabled, system will drift significantly!
[lio_sam_mapFusion_jackal1-11] process has died [pid 10717, exit code -11, cmd /home/tang/catkin_ws/devel/lib/lio_sam/lio_sam_mapFusion __name:=lio_sam_mapFusion_jackal1 _log:=/home/tang/.ros/log/a4793ca8-2d18-11ed-bd50-405bd873e5f9/lio_sam_mapFusion_jackal1-11.log].
log file: /home/tang/.ros/log/a4793ca8-2d18-11ed-bd50-405bd873e5f9/lio_sam_mapFusion_jackal1-11*.log_
DiSCo-SLAM的作者好像不咋回复问题，所以只能请教大佬你了

**Comment by NatureLan-sudo** [comment]
> Hello, 俺也是BIT的研究生（自动化学院）。 这两天在复现DiSCo-SLAM, 自己解决了一下编译问题（主要是libnabo::nabo找不到）。 结果在运行他的kitti_08.bag时候会出错(launch文件的两行替换过了)，不知道大佬有没有类似问题。 _[ WARN] [1662382090.137015156]: Point cloud timestamp not available, deskew function disabled, system will drift significantly! [lio_sam_mapFusion_jackal1-11] process has died [pid 10717, exit code -11, cmd /home/tang/catkin_ws/devel/lib/lio_sam/lio_sam_mapFusion __name:=lio_sam_mapFusion_jackal1 _log:=/home/tang/.ros/log/a4793ca8-2d18-11ed-bd50-405bd873e5f9/lio_sam_mapFusion_jackal1-11.log]. log file: /home/tang/.ros/log/a4793ca8-2d18-11ed-bd50-405bd873e5f9/lio_sam_mapFusion_jackal1-11*.log_ DiSCo-SLAM的作者好像不咋回复问题，所以只能请教大佬你了

校友您好，不好意思，我不做激光，当时仅仅编译了程序并简单看了一下，没有运行复现，后期也没有继续跟进了。你可以检索一下错误，这个错误提示是LOAM部分的一个函数报错的，应该需要再仔细看看。
![image](https://user-images.githubusercontent.com/73154000/188651154-6e538bda-07e3-4bd1-ab22-14120c6495bd.png)
参考CSDN :https://blog.csdn.net/tiancailx/article/details/109494075
